export const users = [
    {
        fullname: 'Maximilian Müller',
        name: 'Maximilian',
        lastname: 'Müller',
        email: 'max.mueller@example.com',
        avatar: 'assets/avatars/Avatar1.svg',
        status: true,
    },
    {
        fullname: 'Anna Schmidt',
        name: 'Anna',
        lastname: 'Schmidt',
        email: 'anna.schmidt@example.com',
        avatar: 'assets/avatars/Avatar2.svg',
        status: true,
    },
    {
        fullname: 'Lukas Fischer',
        name: 'Lukas',
        lastname: 'Fischer',
        email: 'lukas.fischer@example.com',
        avatar: 'assets/avatars/Avatar3.svg',
        status: false,
    },
    {
        fullname: 'Sophia Wagner',
        name: 'Sophia',
        lastname: 'Wagner',
        email: 'sophia.wagner@example.com',
        avatar: 'assets/avatars/Avatar4.svg',
        status: true,
    },
    {
        fullname: 'Felix Becker',
        name: 'Felix',
        lastname: 'Becker',
        email: 'felix.becker@example.com',
        avatar: 'assets/avatars/Avatar5.svg',
        status: false,
    },
    {
        fullname: 'Steffen Hoffmann',
        name: 'Steffen',
        lastname: 'Hoffmann',
        email: 'steffen.hoffmann@example.com',
        avatar: 'assets/avatars/Avatar6.svg',
        status: true,
    }
];